sonar.projectKey=Xiluvele_international-payments-portal-system
sonar.organization=xiluvele

sonar.sources=backend/src,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.coverage.exclusions=**/*

sonar.sourceEncoding=UTF-8